;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝


; ===========================================================
; VARIÁVEIS GLOBAIS
; ===========================================================

[colors]
background     = #292D3E
foreground     = #f0f0f0
primary        = #6D8EC1
secondary      = #e60053
mb             = #34394E
white          = #FFFFFF
red            = #EF5350

;Para ver mais cores: https://kigen.design/color

; ===========================================================
; BARRAS
; ===========================================================

; ---------------------------
; BARRA SUPERIOR
; ---------------------------

[bar/top]
enable-ipc = true
cursor-click = pointer
width = 100%
height = 20pt
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = "JetBrainsMono Nerd Font:size=10;3"
module-margin = 1

border-size = 5
border-color = ${colors.background}

modules-left = arch-icon i3 xwindow 
modules-right = temperature battery bluetooth network cpu memory date


; ---------------------------
; BARRA INFERIOR
; ---------------------------

[bar/bottom]
bottom = true
width = 100%
height = 20pt
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = "JetBrainsMono Nerd Font:size=10;3"
enable-ipc = true
cursor-click = pointer
module-margin = 1

border-size = 5
border-color = ${colors.background}

modules-left = kernel-name updates redshift github
modules-center = music-player volume
modules-right = weather gmail xkeyboard


; ===========================================================
; MÓDULOS
; ===========================================================


; ===========================================================
; SISTEMA
; ===========================================================

[module/uptime]
type = custom/script
exec = uptime -p
interval = 60
format = <label>
label = "%{A1:notify-send "🕒 Sistema Ativo" "$(uptime -p)":}  %{A}"
label-background = ${colors.red}
label-foreground = ${colors.background}
label-padding = 1


[module/kernel-name]
type = custom/script
exec = uname -r | cut -d '-' -f1
interval = 1000

# Estética (mantendo seu padrão de pílula)
format-prefix = " 󰊠 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = " %output% "
label-background = ${colors.primary}

# --- COMANDO DE LIMPEZA ---
# Abre o terminal, executa o script e mantém a janela aberta até o fim
click-right = xfce4-terminal -e "bash /home/ghost/.config/polybar/scripts/clean_system.sh"


[module/cpu]
type = internal/cpu
interval = 2
format = <label>
format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
#label = " %percentage%% "
label-padding = 1
label-background = ${colors.primary}


[module/memory]
type = internal/memory
interval = 2
format = <label>
format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
#label = " %percentage_used%% "
label-padding = 1
label-background = ${colors.primary}


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70
format = <label>
format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = " %temperature-c% "
label-background = ${colors.primary}


[module/updates]
type = custom/script
# Caminho para o teu script
exec = ~/dotfiles/polybar/scripts/updates.sh
# Intervalo de 30 minutos para não pesar no sistema
interval = 1800

# O segredo está aqui: passa o argumento "notify" ao clicar
click-left = ~/dotfiles/polybar/scripts/updates.sh notify

format-prefix = " 󰏗 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = " %output% "
label-background = ${colors.primary}
label-foreground = ${colors.white}


; ===========================================================
; REDE
; ===========================================================

[module/network]
type = internal/network
interface = wlo1

# Usamos tokens de clique direto no label para não ter erro
label-connected = "%{A1:nm-connection-editor:} %essid% %{A}"
label-connected-background = ${colors.primary}

# O prefixo também ganha o clique para a área ficar maior
format-connected = <label-connected>
format-connected-prefix = "%{A1:nm-connection-editor:}   %{A}"
format-connected-prefix-background = ${colors.white}
format-connected-prefix-foreground = ${colors.background}

# Ação de clique direito (Limpeza) em todo o módulo
# A3 = Botão Direito
format-connected-right-click = xfce4-terminal -e "bash /home/ghost/.config/polybar/scripts/clean_system.sh"

[module/network-dynamic]
type = custom/script
exec = ~/.config/polybar/scripts/net_activity.sh
interval = 1
tail = true
format-prefix = " 󰖩 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = "%{A1:xfce4-terminal -e nmtui:} %output% %{A}"
label-background = ${colors.primary}
label-foreground = ${colors.white}
label-padding = 1


; ===========================================================
; ARMAZENAMENTO
; ===========================================================

[module/storage-root]
type = internal/fs
mount-0 = /
interval = 60

format-mounted = <label-mounted>
format-mounted-prefix = "  / "
format-mounted-prefix-background = ${colors.white}
format-mounted-prefix-foreground = ${colors.background}
label-mounted = " %percentage_used%% "
label-mounted-background = ${colors.primary}
label-mounted-foreground = ${colors.white}


[module/storage-home]
type = internal/fs
mount-0 = /home
interval = 60

format-mounted = <label-mounted>
format-mounted-prefix = "  ~ "
format-mounted-prefix-background = ${colors.white}
format-mounted-prefix-foreground = ${colors.background}
label-mounted = " %percentage_used%% "
label-mounted-background = ${colors.primary}
label-mounted-foreground = ${colors.white}

format-unmounted = <label-unmounted>
label-unmounted = %mountpoint% not mounted


; ===========================================================
; ÁUDIO
; ===========================================================

[module/volume]
type = internal/alsa

; --- CONTROLES ---
; O scroll do mouse agora é nativo e atualiza o label NA HORA
master-soundcard = default
master-mixer = Master

; --- FORMATO: TOCANDO ---
format-volume = <ramp-volume><label-volume>
label-volume = " %percentage%% "
label-volume-background = ${colors.primary}
label-volume-foreground = ${colors.foreground}

ramp-volume-background = ${colors.white}
ramp-volume-foreground = ${colors.background}
ramp-volume-padding = 1

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-3 = 󰕾

; --- FORMATO: MUDO ---
format-muted = <label-muted>
format-muted-prefix = " 󰝟 "
format-muted-prefix-background = ${colors.red}
format-muted-prefix-foreground = ${colors.background}

label-muted = " Muted "
label-muted-background = ${colors.primary}
label-muted-foreground = ${colors.white}

; --- AÇÕES EXTRAS ---
; Botão Esquerdo: Mudo (Toggle) + Força atualização visual
click-left = amixer set Master toggle && pkill -USR1 polybar

; Botão Direito: Abre o mixer
click-right = pavucontrol

; ===========================================================
; MÚSICA / PLAYER
; ===========================================================

[module/mpd-player]
type = custom/script
exec = ~/.config/polybar/scripts/player.sh
interval = 2

# --- O ÍCONE ---
# Quando clicar no ícone (prefix), abre o ncmpcpp
format-prefix = "%{A1:xfce4-terminal -e ncmpcpp:} 󰝚 %{A}"
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}

# --- O NOME DA MÚSICA (LABEL) ---
# Botão Direito (A3): Próxima música
# Botão Esquerdo (A1): Música anterior
# Rodinha/Meio (A2): Pause/Play (Toggle)
label = "%{A3:mpc next:}%{A1:mpc prev:}%{A2:mpc toggle:} %output% %{A}%{A}%{A}"
label-background = ${colors.primary}
label-foreground = ${colors.white}
label-padding = 1


[module/buttons]
type = internal/mpd
format-online = <icon-prev> <toggle> <icon-next>
format-background = #6D8EC1
format-online-padding = 1
format-online-background = ${colors.background}
format-online-offset = -32
label-padding = 1

icon-play = " 󰐊 "
icon-pause = " 󰏤 "
icon-stop = " 󰓛 "
icon-prev = " 󰒮 "
icon-next = " 󰒭 "


[module/tidal]
type = custom/script
exec = ~/.config/polybar/scripts/tidal.sh
interval = 2

format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label-background = ${colors.primary}
label-foreground = ${colors.white}
label-padding = 1

# Comandos de Mouse
click-left = playerctl previous && ~/dotfiles/polybar/scripts/tidal_notify.sh
click-right = playerctl next next && ~//dotfiles/polybar/scripts/tidal_notify.sh
scroll-up = playerctl play-pause
scroll-down = playerctl play-pause

[module/music-player]
type = custom/script
exec = ~/dotfiles/polybar/scripts/player_status.sh
interval = 1

; Formato do Módulo
format = <label>
format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
format-overline = ${colors.background}
format-underline = ${colors.background}

; Estilo do Texto
label = " %output% "
label-background = ${colors.primary}
label-foreground = ${colors.white}

; Comandos universais
click-left = playerctl previous && ~/dotfiles/polybar/scripts/tidal_notify.sh
click-right = playerctl next  && ~/dotfiles/polybar/scripts/tidal_notify.sh
click-middle = ~/dotfiles/polybar/scripts/player_notify.sh
scroll-up = playerctl play-pause

; ===========================================================
; DATA E JANELAS
; ===========================================================

[module/date]
type = internal/date
interval = 1.0
time =  %a, %I:%M %p
time-alt = " %A, %d %B %Y"
format = <label>
format-prefix = " 󰥔 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = "%{A1:gsimplecal:} %time% %{A}"
label-background = ${colors.primary}
label-foreground = ${colors.white}
label-padding = 1


[module/xwindow]
type = internal/xwindow
label = %instance%
label-padding = 1
label-foreground = ${colors.foreground}
format-prefix = " 󰇙"
format-prefix-foreground = ${colors.white}


[module/tray]
type = internal/tray
tray-padding = 2px
tray-size = 65%

; ===========================================================
; I3 / WORKSPACES
; ===========================================================

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
strip-wsnumbers = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;󰇚
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;

label-focused = %name%
label-focused-background = ${colors.white}
label-focused-foreground = ${colors.background}
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.white}

label-urgent = %name%
label-urgent-foreground = ${colors.red}
label-urgent-padding = 1


; ===========================================================
; LAYOUT / TECLADO
; ===========================================================

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout><label-indicator>
format-prefix = " 󰌌 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}

label-layout = "%{A1:setxkbmap br:}%{A3:setxkbmap us:} %layout% %{A}%{A}"
label-layout-background = ${colors.primary}
label-layout-foreground = ${colors.foreground}
label-layout-padding = 1

label-indicator-on-capslock = " 󰪛 "
label-indicator-on-capslock-background = ${colors.red}
label-indicator-on-capslock-foreground = ${colors.background}


; ===========================================================
; ENERGIA
; ===========================================================

[module/battery]
type = internal/battery
battery = BAT1
adapter = ADP1
full-at = 99
low-at = 15

# --- ESTADO: DESCARREGANDO ---
# Aqui a mágica acontece: primeiro o ícone (ramp), depois o label
format-discharging = <ramp-capacity><label-discharging>

# Configuramos o fundo branco e a cor do ícone no RAMP, não no prefix
ramp-capacity-0 = "   "
ramp-capacity-1 = "   "
ramp-capacity-2 = "   "
ramp-capacity-3 = "   "
ramp-capacity-4 = "   "
ramp-capacity-background = ${colors.white}
ramp-capacity-foreground = ${colors.background}

# A porcentagem continua com o fundo colorido e o clique
label-discharging = "%{A1:sh -c '~/dotfiles/polybar/scripts/battery_info.sh info' &:} %percentage%% %{A}"
label-discharging-background = ${colors.primary}
label-discharging-foreground = ${colors.white}

# --- ESTADO: CARREGANDO ---
format-charging = <animation-charging><label-charging>

animation-charging-0 = "   "
animation-charging-1 = "   "
animation-charging-2 = "   "
animation-charging-3 = "   "
animation-charging-4 = "   "
animation-charging-background = ${colors.white}
animation-charging-foreground = ${colors.background}
animation-charging-framerate = 750

label-charging = "%{A1:sh -c '~/dotfiles/polybar/scripts/battery_info.sh info' &:} %percentage%% %{A}"
label-charging-background = ${colors.primary}
label-charging-foreground = ${colors.white}


[module/backlight]
type = internal/backlight

# Use o nome que você encontrou no passo 1
card = intel_backlight

# Ativa o scroll do mouse para mudar o brilho
use-actual-brightness = true
enable-scroll = true

# --- ESTÉTICA PÍLULA (Branco | Azul) ---
format = <label>
format-prefix = " 󰃟 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
#label-padding = 1

label = " %percentage%% "
label-background = ${colors.primary}
label-foreground = ${colors.foreground}

# --- AÇÕES ---
# Clique direito abre a limpeza como de costume
click-right = xfce4-terminal -e "bash /home/ghost/.config/polybar/scripts/clean_system.sh"



; ===========================================================
; BLUETOOTH
; ===========================================================

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 2

# Estética
format-prefix = " 󰂯 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = " %output% "
label-background = ${colors.primary}

# --- CLIQUES ---
;Left Click   → Abre menu popup (lista dispositivos / scan / conectar)
click-left = ~/.config/rofi/rofi_bluetooth

; Middle Click → Desconecta dispositivo atual
click-middle = bluetoothctl disconnect

; Right Click  → Liga/Desliga Bluetooth
click-right = bluetoothctl power toggle


; ===========================================================
; PERSONALIZAÇÃO / OUTROS
; ===========================================================

[module/arch-icon]
type = custom/script
exec = echo " "
format = <label>
label = " Arch "
label-background = #6D8EC1
format-prefix = "   "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
click-left = bash ~/.config/rofi/launcher.sh


[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather.sh
interval = 1800 ; 30 minutos

format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}

label = " %output% "
label-background = ${colors.primary}

# Ao clicar com o botão esquerdo, roda o script de notificação
click-left = ~/.config/polybar/scripts/weather_notify.sh
# Clique direito atualiza a barra
click-right = pkill -RTMIN+1 polybar


[module/gmail]
type = custom/script
exec = ~/.config/polybar/scripts/gmail.sh
interval = 120
format-prefix = "   "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}
label = " %output% "
label-background = ${colors.primary}
label-foreground = ${colors.foreground}
click-left = xdg-open https://mail.google.com/

[module/screencast]
type = custom/script
exec = ~/.config/polybar/scripts/screencast-status.sh
interval = 1

click-left = ~/.config/polybar/scripts/record.sh

[module/github]
type = custom/script
exec = ~/dotfiles/polybar/scripts/git_status.sh
interval = 600

format = <label>
format-prefix = " 󰊤 "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}

label = " %output% "
label-background = ${colors.primary}
label-foreground = ${colors.white}

# ADICIONE ESTA LINHA:
click-left = ~/dotfiles/polybar/scripts/git_status.sh check

[module/redshift]
type = custom/script
# Verifica se o processo 'redshift' está rodando
exec = pgrep -x redshift > /dev/null && echo "On" || echo "Off"
# Atualiza a cada 5 segundos
interval = 5

format = <label>
format-prefix = "  "
format-prefix-background = ${colors.white}
format-prefix-foreground = ${colors.background}

label = " %output% "
label-background = ${colors.primary}
label-foreground = ${colors.white}

# Forçamos ele a ler a sua configuração manual
click-left = pgrep -x redshift && pkill redshift || redshift -c ~/.config/redshift/redshift.conf &