[redshift]
# Temperaturas de dia e de noite
temp-day=6500
temp-night=3500

# Transição suave (0 para mudar de uma vez, 1 para gradual)
transition=1

# Localização fixa de Juazeiro do Norte (evita que ele mude sozinho)
location-provider=manual

[manual]
lat=-7.22
lon=-39.32