[redshift]
# Temperaturas (Dia: 5700K / Noite: 3500K para o Catppuccin ficar confortável)
temp-day=5700
temp-night=3500

# Transição suave
transition=1

# Localização manual (Juazeiro do Norte, CE)
location-provider=manual

[manual]
lat=-7.22
lon=-39.33