[redshift]
; Definições de temperatura (Dia/Noite)
temp-day=5700
temp-night=3500

; Transição suave entre dia e noite
transition=1

; Ajuste de brilho (0.1 a 1.0)
brightness-day=1.0
brightness-night=0.8

; Método de ajuste (randr é o padrão para Arch/i3)
adjustment-method=randr

; Localização manual (Juazeiro do Norte)
location-provider=manual

[manual]
lat=-7.22
lon=-39.31